=== WordpressDev/AgilePHP/build/AgilePHP/component.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
# AgilePHP Framework :: The Rapid "for developers" PHP5 framework
# Copyright (C) 2009-2010 Make A Byte, inc

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<!ELEMENT agilephp ( component+, param* )>

<!ELEMENT component ( param*, table* )>
<!ATTLIST component name CDATA #IMPLIED>
<!ATTLIST component version CDATA #IMPLIED>
<!ATTLIST component enabled CDATA #FIXED "false">
<!ATTLIST component language CDATA #IMPLIED>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param name CDATA #IMPLIED>
<!ATTLIST param value CDATA #IMPLIED>

<!ELEMENT table (column*)>
<!ATTLIST table name CDATA #REQUIRED>
<!ATTLIST table model CDATA #REQUIRED>
<!ATTLIST table display CDATA #IMPLIED>
<!ATTLIST table validate CDATA #FIXED "false">
<!ATTLIST table description CDATA #IMPLIED>
<!ATTLIST table isIdentity CDATA #FIXED "true">
<!ATTLIST table isSession CDATA #FIXED "true">

<!ELEMENT column (foreignKey*)>
<!ATTLIST column name CDATA #REQUIRED>
<!ATTLIST column type ( boolean | integer | int | bigint | double | decimal | varchar | float | bit | date | datetime | timestamp | blob | text | password |
						smallint | tinyint | money | char | varbinary | nvarchar | image | uniqueidentifier | smalldatetime | ntext ) "varchar">
<!ATTLIST column length CDATA #IMPLIED>
<!ATTLIST column description CDATA #IMPLIED>
<!ATTLIST column property CDATA #IMPLIED>
<!ATTLIST column display CDATA #IMPLIED>
<!ATTLIST column default CDATA #IMPLIED>
<!ATTLIST column visible CDATA #FIXED "false">
<!ATTLIST column required CDATA #FIXED "true">
<!ATTLIST column primaryKey CDATA #FIXED "true">
<!ATTLIST column autoIncrement CDATA #FIXED "true">
<!ATTLIST column index CDATA #FIXED "true">
<!ATTLIST column sortable CDATA #FIXED "false">
<!ATTLIST column selectable CDATA #FIXED "true">
<!ATTLIST column sanitize CDATA #FIXED "false">

<!ELEMENT foreignKey (#PCDATA)>
<!ATTLIST foreignKey type ( one-to-one | one-to-many | many-to-one | many-to-many ) #REQUIRED>
<!ATTLIST foreignKey name CDATA #REQUIRED>
<!ATTLIST foreignKey table CDATA #REQUIRED>
<!ATTLIST foreignKey column CDATA #REQUIRED>
<!ATTLIST foreignKey controller CDATA #IMPLIED>
<!ATTLIST foreignKey onUpdate ( NO_ACTION | RESTRICT | CASCADE | SET_NULL | SET_DEFAULT ) #IMPLIED>
<!ATTLIST foreignKey onDelete ( NO_ACTION | RESTRICT | CASCADE | SET_NULL | SET_DEFAULT ) #IMPLIED>
<!ATTLIST foreignKey description CDATA #IMPLIED>
<!ATTLIST foreignKey select CDATA #IMPLIED>

=== WordpressDev/AgilePHP/test/components/TestComponent/component.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agilephp SYSTEM "../../../src/component.dtd">
<agilephp>
	<component name="TestComponent" version="0.1">
		<param name="config1" type="string" value="this is a test"/>
		<param name="config2" type="date" value="2010-05-19T04:00:00.000Z"/>
		<param name="config3" type="boolean" value="false"/>
		<param name="config4" type="int" value="123"/>
		<orm>
			<table name="table1" model="TestComponent\model\Table1" description="">
				<column name="id" type="int" length="10" primaryKey="true" autoIncrement="true" visible="false"/>
				<column name="field1" display="Field One" type="varchar" length="255" required="true"/>
				<column name="field2" display="Field Two" type="varchar" length="10" default="Foo"/>
				<column name="field3" property="Table2" display="Table 2" type="int" length="10" sortable="false">
					<foreignKey name="FK_Table1_2" type="many-to-one" onDelete="SET_NULL" onUpdate="CASCADE" 
						table="table2" column="id" controller="TestComponent/table1" select="name"/>
				</column>
			</table>
			<table name="table2" model="TestComponent\model\Table2" description="">
				<column name="id" type="int" length="10" primaryKey="true" autoIncrement="true" visible="false"/>
				<column name="name" type="varchar" length="100" required="true"/>
				<column name="description" type="text"/>
			</table>
		</orm>
	</component>
</agilephp>
